export const ORDER_ALL_REQUEST = 'ORDER_ALL_REQUEST';
export const ORDER_ALL_SUCCESS = 'ORDER_ALL_SUCCESS';
export const ORDER_ALL_FAIL = 'ORDER_ALL_FAIL';
export const ORDER_ALL_RESET = 'ORDER_ALL_RESET';

export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_RESET = 'ORDER_UPDATE_RESET';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const OWN_ORDER_REQUEST = 'OWN_ORDER_REQUEST';
export const OWN_ORDER_SUCCESS = 'OWN_ORDER_SUCCESS';
export const OWN_ORDER_FAIL = 'OWN_ORDER_FAIL';

export const CANCEL_ORDER_REQUEST = 'OWN_ORDER_REQUEST';
export const CANCEL_ORDER_SUCCESS = 'OWN_ORDER_SUCCESS';
export const CANCEL_ORDER_FAIL = 'OWN_ORDER_FAIL';

export const ERRORS_CLEAR = 'ERRORS_CLEAR';
