export const ORDER_ALL_REQUEST = 'ORDER_ALL_REQUEST';
export const ORDER_ALL_SUCCESS = 'ORDER_ALL_SUCCESS';
export const ORDER_ALL_FAIL = 'ORDER_ALL_FAIL';
export const ORDER_ALL_RESET = 'ORDER_ALL_RESET';

export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_RESET = 'ORDER_UPDATE_RESET';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ERRORS_CLEAR = 'ERRORS_CLEAR';
