export const CATEGORY_ALL_REQUEST = 'CATEGORY_ALL_REQUEST';
export const CATEGORY_ALL_SUCCESS = 'CATEGORY_ALL_SUCCESS';
export const CATEGORY_ALL_FAIL = 'CATEGORY_ALL_FAIL';
export const ERRORS_CLEAR = 'ERRORS_CLEAR';

export const NEW_CATEGORY_REQUEST = 'NEW_CATEGORY_REQUEST';
export const NEW_CATEGORY_SUCCESS = 'NEW_CATEGORY_SUCCESS';
export const NEW_CATEGORY_FAIL = 'NEW_CATEGORY_FAIL';
export const NEW_CATEGORY_RESET = 'PRODUCT_NEW_ADMIN_RESET';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_RESET = 'CATEGORY_UPDATE_RESET';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_RESET = 'CATEGORY_DELETE_RESET';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';
