export const WRITE_REVIEW_REQUEST = 'WRITE_REVIEW_REQUEST';
export const WRITE_REVIEW_SUCCESS = 'WRITE_REVIEW_SUCCESS';
export const WRITE_REVIEW_RESET = 'WRITE_REVIEW_RESET';
export const WRITE_REVIEW_FAIL = 'WRITE_REVIEW_FAIL';

export const ALL_PRODUCT_REVIEW_REQUEST = 'ALL_PRODUCT_REVIEW_REQUEST';
export const ALL_PRODUCT_REVIEW_SUCCESS = 'ALL_PRODUCT_REVIEW_SUCCESS';
export const ALL_PRODUCT_REVIEW_FAIL = 'ALL_PRODUCT_REVIEW_FAIL';

export const DELETE_PRODUCT_REVIEW_REQUEST = 'DELETE_PRODUCT_REVIEW_REQUEST';
export const DELETE_PRODUCT_REVIEW_SUCCESS = 'DELETE_PRODUCT_REVIEW_SUCCESS';
export const DELETE_PRODUCT_REVIEW_RESET = 'DELETE_PRODUCT_REVIEW_RESET';
export const DELETE_PRODUCT_REVIEW_FAIL = 'DELETE_PRODUCT_REVIEW_FAIL';

export const ERRORS_CLEAR = 'ERRORS_CLEAR';
