export const WRITE_REVIEW_REQUEST = 'WRITE_REVIEW_REQUEST';
export const WRITE_REVIEW_SUCCESS = 'WRITE_REVIEW_SUCCESS';
export const WRITE_REVIEW_RESET = 'WRITE_REVIEW_RESET';
export const WRITE_REVIEW_FAIL = 'WRITE_REVIEW_FAIL';

export const ERRORS_CLEAR = 'ERRORS_CLEAR';
