export const PRODUCT_ALL_REQUEST = 'PRODUCT_ALL_REQUEST';
export const PRODUCT_ALL_SUCCESS = 'PRODUCT__ALL_SUCCESS';
export const PRODUCT_ALL_FAIL = 'PRODUCT_ALL_FAIL';
export const ERRORS_CLEAR = 'ERRORS_CLEAR';

export const ADMIN_PRODUCT_REQUEST = 'ADMIN_PRODUCT_REQUEST';
export const ADMIN_PRODUCT_SUCCESS = 'ADMIN_PRODUCT_SUCCESS';
export const ADMIN_PRODUCT_FAIL = 'ADMIN_PRODUCT_FAIL';
