export const PRODUCT_NEW_ADMIN_REQUEST = 'PRODUCT_NEW_ADMIN_REQUEST';
export const PRODUCT_NEW_ADMIN_SUCCESS = 'PRODUCT_NEW_ADMIN_SUCCESS';
export const PRODUCT_NEW_ADMIN_FAIL = 'PRODUCT_NEW_ADMIN_FAIL';
export const PRODUCT_NEW_ADMIN_RESET = 'PRODUCT_NEW_ADMIN_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';

export const STOCK_UPDATE_SUCCESS = 'STOCK_UPDATE_SUCCESS';
export const STOCK_UPDATE_FAIL = 'STOCK_UPDATE_FAIL';
export const STOCK_UPDATE_RESET = 'STOCK_UPDATE_RESET';

export const ADD_STOCK_HISTORY = 'ADD_STOCK_HISTORY';
export const DELETE_STOCK_HISTORY = 'DELETE_STOCK_HISTORY';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_ALL_REQUEST = 'PRODUCT_ALL_REQUEST';
export const PRODUCT_ALL_SUCCESS = 'PRODUCT__ALL_SUCCESS';
export const PRODUCT_ALL_FAIL = 'PRODUCT_ALL_FAIL';
export const ERRORS_CLEAR = 'ERRORS_CLEAR';

export const ALL_PRODUCT_REQUEST_HOME = 'ALL_PRODUCT_REQUEST_HOME';
export const ALL_PRODUCT_SUCCESS_HOME = 'ALL_PRODUCT_SUCCESS_HOME';
export const ALL_PRODUCT_FAIL_HOME = 'ALL_PRODUCT_FAIL_HOME';

export const ADMIN_PRODUCT_REQUEST = 'ADMIN_PRODUCT_REQUEST';
export const ADMIN_PRODUCT_SUCCESS = 'ADMIN_PRODUCT_SUCCESS';
export const ADMIN_PRODUCT_FAIL = 'ADMIN_PRODUCT_FAIL';
