const items = {
  products: [
    {
      name: "Cow Milk",
      slug: "Cow Milk",
      category: "Milk",
      image: "/images/milk1.jpg",
      price: 100,
      countInStock: 100,
      rating: 5,
      reviews: 4,
      description: "Pure Milk",
    },
    {
      name: "Buffalo Milk",
      slug: "Buffalo Milk",
      category: "Milk",
      image: "/images/milk2.jpg",
      price: 110,
      countInStock: 100,
      rating: 5,
      reviews: 6,
      description: "Pure Buffalo Milk",
    },
    {
      name: "Dahi",
      slug: "Dahi",
      category: "Yogurt",
      image: "/images/dahi1.jpg",
      price: 130,
      countInStock: 100,
      rating: 5,
      reviews: 4,
      description: "Pure dahi",
    },
    {
      name: "Paneer",
      slug: "Paneer",
      category: "Paneer",
      image: "/images/paneer.jpg",
      price: 850,
      countInStock: 100,
      rating: 5,
      reviews: 4,
      description: "Paneer",
    },
  ],
};
export default items;
